sequenceDiagram
    participant browser
    participant server

    browser->>server: GET html page
    activate server
    Note left of server: sends html page
    deactivate server:
    Note right of browser: browser does not need to request additional pages while in the SPA
